# Generated by Django 5.0 on 2024-02-02 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0002_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.holiday'),
        ),
    ]
