# Generated by Django 5.0 on 2024-02-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_alter_attendance_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_comment',
            name='employee',
        ),
        migrations.AddField(
            model_name='attendance_comment',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.attendance'),
        ),
    ]
