# Generated by Django 5.0 on 2024-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_remove_attendance_comment_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_comment',
            name='month',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_comment',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
