# Generated by Django 5.0 on 2024-02-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0008_alter_attendance_comment_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_comment',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance_comment',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
