# Generated by Django 5.0 on 2024-02-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0011_bloodgroup'),
        ('Register_Login', '0009_paymenttermsupdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='holiday',
        ),
        migrations.CreateModel(
            name='employee_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('Action', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payroll_employee')),
                ('login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
